import TodosProvider from '@/components/TodosContext';
import '../globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "",
    template: "%s | Todo App",
  },
  description: 'Generated by Next.js',
}

type Props = {
  children: React.ReactNode,
}

export default function RootLayout({ children }: Props) {
 return (
    <html lang="en">
      <TodosProvider>
        <body className="flex items-center justify-cent w-screen">
          <main className="flex items-center 
            justify-center h-screen w-[100%] 
            rounded-md px-[50px] bg-gradient-to-r from-yellow-100 via-yellow-300 to-yellow-500"
          >
            {children}
          </main>
        </body>
      </TodosProvider>
    </html>
  );
}
